services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: parking_user      # Замените на свои значения
      POSTGRES_PASSWORD: parking_pass  # Замените на свои значения
      POSTGRES_DB: parking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin      # Замените для продакшена!
      MINIO_ROOT_PASSWORD: minioadmin  # Замените для продакшена!
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio_data:/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@parking.com  # Замените на свой email
      PGADMIN_DEFAULT_PASSWORD: admin_parking   # Замените на свой пароль
    ports:
      - "5050:80"
    depends_on:
      - db
  redis:  # Добавляем Redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_data:
  minio_data:
  redis_data: