# Generated by Django 5.2 on 2025-04-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='description_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='parking',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
